version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: node --version
      - run: touch version.txt
      - run: echo "node version test" > version.txt
      - store_artifacts:
        path: version.txt